const express = require('express')
const router = express.Router()
const signup = require('./signup')
const login = require('./login')
const {verifyEmail,changePassword} = require('./forgetPassword')
router.post('/signup' , signup)
router.post('/login' , login)
router.post('/forget-password' , verifyEmail)
router.put('/reset-password' , changePassword)
module.exports  = router